/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agh.cs.gameoflife;

public class Main {
    public static void main(String[] args) {
        WorldApplication.main(new String[]{});
    }
}
